version: '3.7'
services:
  postgresd:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=admin
